name: "Amazing 3D floorplan!"
description: "My first real looooladd-on!"
slug: "hello_world2"
image: dr.kirottu.net/my-addon
version: "69.69.69"
init: false
arch:
  - aarch64
  - amd64
startup: services
ingress: true
ingress_panel: true
panel_icon: mdi:cog
panel_title: "My Add-on"
map:
 - type: homeassistant_config
   read_only: False
 - type: addon_config
   read_only: False
ports:
  8099/tcp: 8099

